apiVersion: v1
kind: Namespace
metadata:
  name: demo


---

apiVersion: cacerts.csi.cert-manager.io/v1alpha1
kind: CAProviderClass
metadata:
  name: ca-provider
  namespace: demo
spec:
  refs:
  - apiGroup: cert-manager.io
    kind: Issuer
    # namespace:
    name: ca-issuer

---

apiVersion: v1
kind: Pod
metadata:
  name: curl-alpine
  namespace: demo
spec:
  containers:
  - name: main
    # image: curlimages/curl
    # env:
    # - name: CURL_CA_BUNDLE
    #   value: /etc/ssl/cert.pem
    image: appscode/curl:alpine
    command:
    - sleep
    - "3600"
    volumeMounts:
    - name: cacerts
      mountPath: /etc/ssl/certs
  volumes:
  - name: cacerts
    csi:
      driver: cacerts.csi.cert-manager.io
      readOnly: true
      volumeAttributes:
        os: alpine
        caProviderClasses: ca-provider

---

apiVersion: v1
kind: Pod
metadata:
  name: curl-alpine-noca
  namespace: demo
spec:
  containers:
  - name: main
    # image: curlimages/curl
    # env:
    # - name: CURL_CA_BUNDLE
    #   value: /etc/ssl/cert.pem
    image: appscode/curl:alpine
    command:
    - sleep
    - "3600"
