/*
Copyright AppsCode Inc. and Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "kubeops.dev/csi-driver-cacerts/apis/cacerts/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCAProviderClasses implements CAProviderClassInterface
type FakeCAProviderClasses struct {
	Fake *FakeCacertsV1alpha1
	ns   string
}

var caproviderclassesResource = schema.GroupVersionResource{Group: "cacerts.csi.cert-manager.io", Version: "v1alpha1", Resource: "caproviderclasses"}

var caproviderclassesKind = schema.GroupVersionKind{Group: "cacerts.csi.cert-manager.io", Version: "v1alpha1", Kind: "CAProviderClass"}

// Get takes name of the cAProviderClass, and returns the corresponding cAProviderClass object, and an error if there is any.
func (c *FakeCAProviderClasses) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.CAProviderClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(caproviderclassesResource, c.ns, name), &v1alpha1.CAProviderClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CAProviderClass), err
}

// List takes label and field selectors, and returns the list of CAProviderClasses that match those selectors.
func (c *FakeCAProviderClasses) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.CAProviderClassList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(caproviderclassesResource, caproviderclassesKind, c.ns, opts), &v1alpha1.CAProviderClassList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.CAProviderClassList{ListMeta: obj.(*v1alpha1.CAProviderClassList).ListMeta}
	for _, item := range obj.(*v1alpha1.CAProviderClassList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested cAProviderClasses.
func (c *FakeCAProviderClasses) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(caproviderclassesResource, c.ns, opts))

}

// Create takes the representation of a cAProviderClass and creates it.  Returns the server's representation of the cAProviderClass, and an error, if there is any.
func (c *FakeCAProviderClasses) Create(ctx context.Context, cAProviderClass *v1alpha1.CAProviderClass, opts v1.CreateOptions) (result *v1alpha1.CAProviderClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(caproviderclassesResource, c.ns, cAProviderClass), &v1alpha1.CAProviderClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CAProviderClass), err
}

// Update takes the representation of a cAProviderClass and updates it. Returns the server's representation of the cAProviderClass, and an error, if there is any.
func (c *FakeCAProviderClasses) Update(ctx context.Context, cAProviderClass *v1alpha1.CAProviderClass, opts v1.UpdateOptions) (result *v1alpha1.CAProviderClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(caproviderclassesResource, c.ns, cAProviderClass), &v1alpha1.CAProviderClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CAProviderClass), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCAProviderClasses) UpdateStatus(ctx context.Context, cAProviderClass *v1alpha1.CAProviderClass, opts v1.UpdateOptions) (*v1alpha1.CAProviderClass, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(caproviderclassesResource, "status", c.ns, cAProviderClass), &v1alpha1.CAProviderClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CAProviderClass), err
}

// Delete takes name of the cAProviderClass and deletes it. Returns an error if one occurs.
func (c *FakeCAProviderClasses) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(caproviderclassesResource, c.ns, name), &v1alpha1.CAProviderClass{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCAProviderClasses) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(caproviderclassesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.CAProviderClassList{})
	return err
}

// Patch applies the patch and returns the patched cAProviderClass.
func (c *FakeCAProviderClasses) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.CAProviderClass, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(caproviderclassesResource, c.ns, name, pt, data, subresources...), &v1alpha1.CAProviderClass{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.CAProviderClass), err
}
